{% set version = load_file_contents("VERSION").strip() %}

package:
  name: metamalevich
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    mkdir -p $PREFIX/share/metamalevich/cpp
    cp cpp/*.cpp $PREFIX/share/metamalevich/cpp/
  entry_points:
    - metamalevich = metamalevich.cli:main

requirements:
  host:
    - python 3.12.14
    - pip
    - setuptools 84.0.0
  run:
    - python 3.12.14
    - numpy 2.5.3
    - pyyaml 6.0.3
    - pandas 3.0.6
    - altair 6.2.2
    - gxx_linux-64 16.2.0

test:
  imports:
    - metamalevich
  commands:
    - metamalevich --version

about:
  home: https://github.com/dsmutin/metaMalevich
  license: MIT
  license_file: LICENSE
  summary: "Improve metagenomic taxonomic re-profiling with coloured assembly graphs"
