{% set version = load_file_contents("VERSION").strip() %}

package:
  name: metamalevich
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - metamalevich = metamalevich.cli:main

requirements:
  host:
    - python 3.12
    - pip
    - setuptools
  run:
    - python 3.12

test:
  imports:
    - metamalevich
  commands:
    - metamalevich --version

about:
  home: https://github.com/dsmutin/metaMalevich
  license: MIT
  license_file: LICENSE
  summary: "Improve metagenomic taxonomic re-profiling with coloured assembly graphs"
